### ISSUE TITLE
What's your keyboard/mouse?

### ISSUE THREAD

**Issue by insanehong** [SBoudrias/ama#11]

**Comment by SBoudrias** [comment]
At home (for open source stuff), I usually only use my macbook keyboard and trackpad.

At work I have a detached mac full keyboard and a pretty cheap mouse. I'll see if I think to take a picture on Monday.

Funny thing maybe is I set my american keyboard as French Canadian layout and never got my head around learning another layout.

**Comment by SBoudrias** [comment]
Here's a photo

![img_0017](https://cloud.githubusercontent.com/assets/923865/8786098/3046144c-2ee1-11e5-828f-166e9c079b07.JPG)

And some extra details from my work desk :stuck_out_tongue_closed_eyes:

**Comment by insanehong** [comment]
:+1:
