### ISSUE TITLE
What's your favorite t-shirt (that you own)? Selfie!

### ISSUE THREAD

**Issue by silvenon** [SBoudrias/ama#12]

**Comment by SBoudrias** [comment]
Oh, it's a bear playing accordion! From [Canailles](https://canailles.bandcamp.com/)

![img_0019](https://cloud.githubusercontent.com/assets/923865/8842121/e9db36d8-30aa-11e5-8519-8701baf37fb4.JPG)

**Comment by SBoudrias** [comment]
Haaaa nice demo of the jpeg encoding bug!! - I swear that photo was in the right way before uploading :laughing:

**Comment by silvenon** [comment]
Awesome! :+1: 

Yeah, I get that too, when I was pulling a photo from Flickr, the thumbnail was correctly positioned, but a larger version was rotated by 90 degrees. Not sure what that is about…
