### ISSUE TITLE
Do you participate in mentoring or coaching others?

### ISSUE THREAD

**Issue by jedireza** [SBoudrias/ama#18]

**Comment by SBoudrias** [comment]
I did some consultation work 2-3 years ago, mostly around mobile web and promotion through social media. And I teached a course on Wordpress as a college night class. These two experience were not my favorites ones, I felt we couldn't really go in depth into programming issues.

As of now, I only contribute to my team learning lunches from time to time, and I sometime get assigned as mentors to interns and new hires.
