### ISSUE TITLE
Subject trend year

### ISSUE THREAD

**Issue by juanespina** [SBoudrias/ama#21]
What do you think will be most talked about and studied this year, example API, Spec and tools.

**Comment by SBoudrias** [comment]
I don't think we'll see a lot of new tools or library this year. I think we'll see more and more focus on writing maintainable code - functional concepts, explicit dependencies and clarity.

This have been kind of ignored by the community over the last few years, but as we start having solid tools with great maintainers, I believe the focus will switch more to the core of what programming is actually about. Less hacks and more professional endeavor.
