### ISSUE TITLE
Feature EcmaScript detection 

### ISSUE THREAD

**Issue by juanespina** [SBoudrias/ama#22]
you think interesting to have something like [feature.js](http://featurejs.com/) to the features of EcmaScript?

**Comment by SBoudrias** [comment]
To be honest, probably not.

In the past I used a lot of polyfill and modernizr - but that was always to provide a seamless fallback (seamless to the user and to me) to important technologies.

Knowing if a language feature is there or not doesn't really help me write better program, I'd just write in the most commonly supported language or use a compiler like Babel. To me, there's no point writing features twices in two version of a language as this would double the number of potential bugs you have.
