### ISSUE TITLE
If i want be like you, where i have to start?

### ISSUE THREAD

**Issue by sukrosono** [SBoudrias/ama#23]
Like i need a map to find you dude :smiling_imp:

**Comment by SBoudrias** [comment]
First of all, there's no magic ingredient and anyone's totally able to do what I do.

I'd say:
1. Contributing to Open Source helps you become a better developer.
2. Peer feedback and code review at your workplace are incredible learning experiences.
3. Always try to see the big picture when you code; what's my goal, how can I clearly describe what I'm doing. Too many people focus on narrow details (code style, etc). Keeping the global goal in mind helps a lot.
4. Be a team player! Your team is most of what you are and what you ship.
5. Keep on learning everyday.

**Comment by sukrosono** [comment]
1. and 2. Sure i will.
2. Where my problem is. Sometimes i just think i have to know this thing, i love code and all stuff about it. But sometimes i get to far. I get the poin anyway, i just not sure which one i should skip or not. Like recenly i skip writing unit test, and ig it will help me alot if i m not skip it (I am stuck over 1 week) . Did you think it should be like this? so i have to read more before code?
3. Yes it think about it, since deadline killing me when be a single fighter. But when i can i will do it myself.
4. Sometimes i really confuse which i have to learn first. :worried: 
   Any advice will help, since i pretty sure when person who have more experience say it. Because it make me sure that the path is right.
   Thank dude, it help me

**Comment by SBoudrias** [comment]
Technologies and libraries are not the main one you should focus on.

General concepts and programming language knowledge is more useful and is it reusable everywhere. Once you know these concepts, any tools/library you encounter will be way easier to understand.

**Comment by sukrosono** [comment]
So the core language itself right?
Thanks, it will be my first priority
:relieved:
