### ISSUE TITLE
How design good software or apps?

### ISSUE THREAD

**Issue by sukrosono** [SBoudrias/ama#24]
i just realize that lately i design it myself, code it myself, and destroy it myself. Any article or literature may help me,

**Comment by SBoudrias** [comment]
I'm not sure I understand your question correctly. But I'm not designing the product I work on daily, Yelp Seatme have a design/product team in charge of the product design and features.

**Comment by sukrosono** [comment]
I mean the design of project before code it, like it's spec or cope. I wonder how to stay `dry` and code re-usability. Sorry become unclear :confused:

**Comment by SBoudrias** [comment]
Well, I think this is a little bit personal for each person and the way their brain is wired.

I personally usually start by reading the prior code, build a vague idea of how my code will fit in there and then I'll start coding. Then I go over my `git diff` a lot refactoring and simplifying what I know to be dirty. Sometime, I'll also branch off some refactoring task to be completed on the old code before inserting my new feature - ideally you want to keep the code review diff minimals, so splitting in smaller task helps to keep the context of your changes.

As a rule of thumb, some rules I try to follow:
- Don't use classes - don't use `this`
- Pass contextual data as arguments (dependency injection)
- Rely on CSS as much as possible (like don't position stuff through JS)
- Prefer boilerplate to implicit dependencies (I prefer code that is more verbose but explicit)
- Keep functions small and focused on a single task
- Don't rely on state

**Comment by sukrosono** [comment]
> - Keep functions small and focused on a single task

when the task is big, separate them into smaller function? Maybe some of them re-usable, am i correct?

> - Don't rely on state

what kind of state? sorry i just stupid :confused: 

Thanks Simon, you are really cool :smile:

**Comment by SBoudrias** [comment]
> when the task is big, separate them into smaller function? Maybe some of them re-usable, am i correct?

Yes, that's correct. But the number of lines is not what qualify a function as being big, it's the number of concern.

You don't want to abstract away common patterns your team know about (like the ORM or date handling, etc)

> what kind of state?

Anything that is kept between runs. So anything on `this` or any values kept in a closure.
