### ISSUE TITLE
How and when did you get into doing open source?

### ISSUE THREAD

**Issue by sindresorhus** [SBoudrias/ama#3]

**Comment by SBoudrias** [comment]
It's hard to say exactly when, but I'd say 3 or 4 years ago. (Someone should do an app to fetch a user first contribution on Github - we could all see our newb mistake over again!)

Basically, we needed a more powerful frontend JS infrastructure at the company I worked for at the time. Backbone.js had been released a few months back, and already it was taking over the JavaScript community. Out of need, I joined the bandwagon and found myself starting to get involved into some community, mostly Require.js, Backbone-Boilerplate and LayoutManager.

Before that, I wrote a couple tutorials on [alsacréations](http://www.alsacreations.com/) (a french frontend dev community). I also remembered open sourcing a couple PHP scripts on my blog - at the time I didn't knew anything about git, so it was basically a bunch of `.zip` packages. That might seem like a long shot, but I released all of them with their own blog post in french. As there's not that much french resource on programming, these packages actually got a fair successes (and I still to this day get emails about these snippets -sick-)
