### ISSUE TITLE
What question do you hate to answer?

### ISSUE THREAD

**Issue by sindresorhus** [SBoudrias/ama#6]

**Comment by SBoudrias** [comment]
I'm usually a very open person. There's very few questions that would shock me - or wouldn't get an answer.

But I can tell you about one specific question that really annoys me everytime. When someone from France ask me where I learned to speak french (One of them actually told me I was very good at it :laughing:)

**Comment by sindresorhus** [comment]
Why does that annoy you? I'm not following.

**Comment by yoannmoinet** [comment]
Where did you learn to speak French? 
Because you're really good at it, almost as fluent as a francophone :sweat_smile:.
